### ISSUE TITLE
bqplot under python 3.9?

### ISSUE THREAD

**Issue by JuanCab** [conda-forge/bqplot-feedstock#69]
I normally install packages from conda-forge... noticed bqplot was not available under python 3.9 yet. Is this an issue with the condo-forge feedstock of bqplot or is there a problem with bqplot under python 3.9?

**Comment by JuanCab** [comment]
I assume this is just an issue with the feedstock being updated to support Python 3.9 but am not certain (I haven't had much experience with conda-forge feedstocks except as a user.

**Comment by jasongrout** [comment]
It's a noarch feedstock, so it should just work in python 3.9.

However, it depends on traitlets<5, but it looks like traitlets 4 is not built for python 3.9. So the real question here is: can bqplot use traitlets 5? If so, I think the feedstock (and python package) should be updated.

**Comment by jasongrout** [comment]
The python package just says traitlets >= 4.3: https://github.com/bqplot/bqplot/blob/e330ebefc41b5abfe979c5ce11e186488b5016a2/setup.py#L134

**Comment by jasongrout** [comment]
#70 may fix this issue, as it allows bqplot to use traitlets 5 (we already allowed it for pip installs, this is just updating the conda recipe).

**Comment by martinRenou** [comment]
Should be fixed with the coming 0.12.20
